### PR TITLE
fix/prettier tsconfig 작동안하는 현상 오버라이드 및 해결

### PR DESCRIPTION
**Pull request by 05lazy**
Until now your service would not have worked prettier. 😸😸
I solved it and reused tsconfig and prettier when overridden.

- prettier sdks fixes
- tsconfig,  prettier override

### CODE REVIEW

**Comment by eungyeole** [comment]
Oh, looks good, 
but in my opinion husky template not changes.
Can you change husky template?, when this work is complete, I will give this PR an approval

**Comment by eungyeole** [comment]
@05lazy my mistake, I wanted to say `hygen template`

**Review by 05lazy — COMMENTED** [review]
@eungyeole, Edit completed. Is this what you were hoping for??

**Review by eungyeole — APPROVED** [review]
👍

**Comment by eungyeole** [comment]
@05lazy 도커 빌드 오류 땜시 main branch 롤백 해서 pr 3개 다시 올려 주면 수정후에 머지 예정

**Pull request merged**
